services:
  db1:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_DATABASE=${MSSQL_DATABASE}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data1:/var/opt/mssql

  db2:
    image: mysql:8.1
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PROJECT2_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_PROJECT2_DATABASE}
      - MYSQL_USER=${MYSQL_PROJECT2_USER}
      - MYSQL_PASSWORD=${MYSQL_PROJECT2_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data2:/var/lib/mysql

  # db3:
  #   image: mysql:8.1
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_PROJECT3_ROOT_PASSWORD}
  #     - MYSQL_DATABASE=${MYSQL_PROJECT3_DATABASE}
  #     - MYSQL_USER=${MYSQL_PROJECT3_USER}
  #     - MYSQL_PASSWORD=${MYSQL_PROJECT3_PASSWORD}
  #   ports:
  #     - "3307:3306"
  #   volumes:
  #     - mysql_data3:/var/lib/mysql

  project1:
    build:
      context: ./project1
      dockerfile: Dockerfile
    volumes:
      - ${FUEL_PROJECT1_PATH:-/path/to/project_src1}:/var/www/html
    environment:
      - DB_CONNECTION=sqlsrv
      - DB_HOST=db1
      - DB_PORT=1433
      - DB_DATABASE=${MSSQL_DATABASE}
      - DB_USERNAME=sa
      - DB_PASSWORD=${MSSQL_SA_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db1

  project2:
    build:
      context: ./project2
      dockerfile: Dockerfile
    volumes:
      - ${FUEL_PROJECT2_PATH:-/path/to/project_src2}:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db2
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_PROJECT2_DATABASE}
      - DB_USERNAME=${MYSQL_PROJECT2_USER}
      - DB_PASSWORD=${MYSQL_PROJECT2_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - db2

  project3:
    build:
      context: ./project3
      dockerfile: Dockerfile
    volumes:
      - ${LARAVEL_PROJECT3_PATH:-/path/to/project_src3}:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db2
      - DB_PORT=3306
      - DB_DATABASE=${MYSQL_PROJECT3_DATABASE}
      - DB_USERNAME=${MYSQL_PROJECT3_USER}
      - DB_PASSWORD=${MYSQL_PROJECT3_PASSWORD}
    ports:
      - "8083:80"
    depends_on:
      - db2

volumes:
  mssql_data1:
  mysql_data2:
  mysql_data3:
